#!/bin/bash

# when execute within Moodle Git repository, the script displays all the information
# required to fill a pull request for the current branch

#
# the current branch name
#
BRANCHNAME=$(git branch 2> /dev/null | grep -e ^*\  | tr -d \*\ )

#
# current branch HEAD
#
BRANCHHASH=$(git rev-parse $BRANCHNAME)

#
# tracked (upstream) branch name
#
BASENAME=$(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD))

if [ -z "$BASENAME" ]; then
    echo "Unable to determine the tracked upstream branch - try rebase"
    exit 100
fi

#
# tracked (upstream) branch hash
#
BASEHASH=$(git rev-parse $BASENAME)

#
# display the info for the pull request
#
echo "Pull From Repository: git://github.com/mudrd8mz/moodle.git"
echo "Pull Branch:          $BRANCHNAME"
echo "Pull Diff URL:        https://github.com/mudrd8mz/moodle/compare/$BASEHASH...$BRANCHHASH"
